name: Deploy Java application via Terraform

on:
    push:
        branches:
            - main
            - feature/pipline-enhancement
        tags:
            - 'deploy-dev'
            - 'deploy-prod'
    
jobs:
    Terraform-deployment:
        name: terraform deploy
        runs-on: ubuntu-latest

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Terrraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.6.6

            - name: Determine stage
              id: get-stage
              run: |
               if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
                  echo "stage=dev" >> "$GITHUB_OUTPUT"

               elif [[ "${GITHUB_REF}" == "refs/heads/feature/pipline-enhancement" ]]; then
                  echo "stage=dev" >> "$GITHUB_OUTPUT"

               elif [[ "${GITHUB_REF}" == "refs/tags/deploy-prod" ]]; then
                  echo "stage=prod" >> "$GITHUB_OUTPUT"

               
               elif [[ "${GITHUB_REF}" == "refs/tags/deploy-dev" ]]; then
                  echo "stage=dev" >> "$GITHUB_OUTPUT"
               else
                  echo "Unsupported ref: ${GITHUB_REF}"
                  exit 1
               fi
            
            - name: Terraform Init
              run: terraform init

            - name: Import ec2-write-only-profile (IAM instance profile)
              run: terraform import -input=false -var-file="${{ steps.get-stage.outputs.stage }}_config.tfvars" aws_iam_instance_profile.ec2_instance_profile ec2-write-only-profile || true

            - name: Import ec2-read-only-profile (IAM instance profile)
              run: terraform import -input=false -var-file="${{ steps.get-stage.outputs.stage }}_config.tfvars" aws_iam_instance_profile.read_instance_profile ec2-read-only-profile || true

            - name: Terraform Formating
              run: terraform fmt -check
              
            - name: Terrraform syntax validation
              run: terraform validate

            - name: Terraform plan
              run: terraform plan -var-file="${{ steps.get-stage.outputs.stage }}_config.tfvars"

            - name: Terraform Apply
              run: terraform apply -auto-approve -var-file="${{ steps.get-stage.outputs.stage }}_config.tfvars"

            

            
              #run this for loop 15 times but after each loop stop for 10 sec then agian iterate
            - name: Wait for EC2 to be ready on port 80 !!!
              run: |

                  set +e

                  EC2_PUBLIC_IP=$(terraform output -raw aws_Main_instance_Public_Ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
                  echo "EC2 IP: $EC2_PUBLIC_IP"

                  echo "Sleeping 80 seconds to let app boot..."
                  sleep 80

                  echo "Curling http://$EC2_PUBLIC_IP"
                  STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://$EC2_PUBLIC_IP)
                  echo "HTTP Status: $STATUS"

#ed